# Requires ttBld.exe version 1.0.0 or higher to process

Options:
    Project:     ttTrace      # project name
    Pch:         pch.h        # "none" or name of header file to use for precompilation
    Exe_type:    window       # [window | console | lib | dll]
    Optimize:    space        # [space | speed] optimization to use in release builds
    Warn:        4            # [1-4] warning level
    Crt_rel:     dll          # [static | dll] type of CRT to link to in release builds
    Crt_dbg:     dll          # [static | dll] type of CRT to link to in debug builds

    CFlags_cmn: -std:c++17 /Zc:__cplusplus

    TargetDir: ../bin         # 64-bit target directory

    Natvis:      ../../ttlib/ttlibwin.natvis # MSVC Debug visualizer

    IncDirs:     ../include;../WTL/include                 # additional directories for header files
    BuildLibs:   ../src       # libraries that need to be built (added to makefile generation)

Files:
    trace.rc
    mainapp.cpp

    traceview.cpp
    mainfrm.cpp
    prefs.cpp
