# Requires ttBld.exe version 1.4.0 or higher to process

# This is primarily for use in testing ttLib functionality. Most callers should build ttLib.lib and only build
# ttLibwin.lib if they need the additional Windows functionality.

Options:
    Project:    ttLiball   # project target name
    Exe_type:   lib        # [window | console | lib | dll]
    Pch:        pch.h      # precompiled header
    Pch_cpp:    winsrc/pch.cpp

    Optimize:   space      # [space | speed] optimization
    Warn:       4          # [1-4]

    CFlags_cmn: -std:c++17 /Zc:__cplusplus -DTTALL_LIB # flags to pass to the compiler in all builds

    Crt_rel:    dll        # [static | dll] type of CRT to link to in release builds
    Crt_dbg:    dll        # [static | dll] type of CRT to link to in debug builds

    IncDirs:    winsrc/precompile;include
    TargetDir:  lib

Files:
    # These files should be moved to ../src once they can be compiled without Windows

    winsrc/ttbasethread.cpp    # ttCBaseThread class
    winsrc/tthashpair.cpp      # ttCHashPair
    winsrc/ttmultithread.cpp   # ttCMultiThrd class
    winsrc/ttprintf.cpp        # printf
    winsrc/ttstr.cpp           # ttCStr class
    winsrc/ttmisc.cpp          # miscellaneous functions
    winsrc/ttstrfuncs.cpp      # string handling and ttStr class

    # This is obsolete and should be replaced with pugixml!
    winsrc/ttxml.cpp

    # This is obsolete and should be replaced by ttTextFile or ttTextView
    winsrc/ttlinefile.cpp

# Windows only files

    winsrc/ttdebug.cpp         # debug and assertion handling
    winsrc/ttdib.cpp           # ttCDib class
    winsrc/ttdirdlg.cpp        # dialog for selecting a directory
    winsrc/ttdlg.cpp           # ttCDlg class
    winsrc/ttfile.cpp          # ttCFile class
    winsrc/ttfiledir.cpp       # file and directory handling
    winsrc/ttfiledlg.cpp       # ttCFileDlg class
    winsrc/ttheap.cpp          # ttCHeap class
    winsrc/ttlist.cpp          # ttCList class
    winsrc/ttmultibtn.cpp      # ttCMultiBtn class
    winsrc/ttshadebtn.cpp      # ttCShadeBtn class
    winsrc/ttwin.cpp           # ttCWin class
    winsrc/ttwinmisc.cpp       # Miscellaneous functions for use on Windows
    winsrc/ttwstr.cpp          # Wide-character string class

# ttLib files
    src/ttconsole.cpp    # class that sets/restores console foreground color
    src/ttcstr.cpp       # Class for handling zero-terminated char strings.
    src/ttcview.cpp      # string_view functionality on a zero-terminated char string.
    src/ttenumstr.cpp    # ttEnumStr, ttEnumStr
    src/ttformat.cpp     # ttString::Printf(...)
    src/ttlibspace.cpp   # ttlib namespace functions
    src/ttpath.cpp       # Contains functions for working with filesystem::path and filesystem::directory
    src/ttnamespace.cpp  # tt namespace functions
    src/ttstring.cpp     # std::string class with some additional functionality
    src/tttextfile.cpp   # Class for reading and writing text files.
    src/ttTR.cpp         # Function for translating strings
