# Requires ttBld.exe version 1.2.0 or higher to process
#
# This builds a libary that links statically to the C++ standard library and compiler runtime support libraries.

Options:
    Project:     ttLibs       # project name
    Exe_type:    lib          # [window | console | lib | dll]
    Crt_rel:     static       # [static | dll] type of CRT to link to in release builds
    Crt_dbg:     static       # [static | dll] type of CRT to link to in debug builds

    Pch:         pch.h           # name of precompiled header file, or "none" if not using precompiled headers
    Pch_cpp:     ../src/pch.cpp  # source file used to build precompiled header (default uses same name as PCH option)

    Optimize:    space        # [space | speed] optimization to use in release builds
    Warn:        4            # [1-4] warning level

    64Bit:       true         # [true | false] indicates if project can be built as a 64-bit target
    TargetDir64: ../lib64     # 64-bit target directory
    32Bit:       true         # [true | false] indicates if project can be built as a 32-bit target
    TargetDir32: ../lib32     # 32-bit target directory

    IncDirs:     ../src       # additional directories for header files

Files:
    .include ../src/.srcfiles.yaml
