# Requires ttBld.exe version 1.0.0 or higher to process

Options:
    Project:    ttLib   # project target name
    Exe_type:   lib        # [window | console | lib | dll]
    Pch:        pch.h      # precompiled header
    Optimize:   space      # [space | speed] optimization
    Warn:       4          # [1-4]

    CFlags_cmn: -std:c++17 /Zc:__cplusplus # flags to pass to the compiler in all builds

    Crt_rel:    dll        # [static | dll] type of CRT to link to in release builds
    Crt_dbg:    dll        # [static | dll] type of CRT to link to in debug builds

    IncDirs:    precompile;../include
    TargetDir:  ../lib

Files:
    ttTR.cpp        # Function for translating strings
    ttconsole.cpp   # class that sets/restores console foreground color
    ttenumstr.cpp   # ttEnumStr, ttEnumStr
    ttpath.cpp      # Contains functions for working with filesystem::path and filesystem::directory
    ttformat.cpp    # ttString::Printf(...)
    ttstring.cpp    # std::string class with some additional functionality
    tttextfile.cpp  # Class for reading and writing text files.
