# Requires ttBld.exe version 1.0.0 or higher to process

Options:
    Project:     ttLib        # project target name
    Exe_type:    lib          # [window | console | lib | dll]
    PCH:         pch.h        # precompiled header
    Optimize:    space        # [space | speed] optimization
    WarnLevel:   4            # [1-4]
    CrtRel:      static       # [static | dll] type of CRT to link to in release builds
    CrtDbg:      static       # [static | dll] type of CRT to link to in debug builds

    64Bit:       true         # create 64-bit project as well as 32-bit project
    TargetDir64: ../lib64     # 64-bit target directory
    32Bit:       true         # if true, build 32-bit target
    TargetDir32: ../lib32     # 32-bit target directory

Files:
    ttfiledir.cpp       # file and directory handling
    ttmisc.cpp          # miscellaneous functions
    ttstrfuncs.cpp      # string handling and ttStr class
    ttbasethread.cpp    # ttCBaseThread class
    ttdebug.cpp         # debug and assertion handling
    ttdirdlg.cpp        # dialog for selecting a directory
    ttenumstr.cpp       # ttCEnumStr class
    ttfile.cpp          # ttCFile class
    tthashpair.cpp      # ttCHashPair
    ttheap.cpp          # ttCHeap class
    ttlist.cpp          # ttCList class
    ttmultithread.cpp   # ttCMultiThrd class
    ttprintf.cpp        # printf
    ttstr.cpp           # ttCStr class
    ttwstr.cpp          # ttCWStr class
    ttxml.cpp           # ttCParseXML class

# Windows only files

    ttdib.cpp           # ttCDib class
    ttdlg.cpp           # ttCDlg class
    ttfiledlg.cpp       # ttCFileDlg class
    ttmultibtn.cpp      # ttCMultiBtn class
    ttshadebtn.cpp      # ttCShadeBtn class
    ttwin.cpp           # ttCWin class
    ttwinmisc.cpp       # Miscellaneous functions for use on Windows
