# Requires ttBld.exe version 1.4.0 or higher to process -- see https://github.com/KeyWorksRW/ttBld

Options:
    Project:    ttLib   # project target name
    Exe_type:   lib     # [window | console | lib | dll]
    Pch:        pch.h   # precompiled header
    Optimize:   space   # [space | speed] optimization
    Warn:       4       # [1-4]

    CFlags_cmn: -std:c++17 /Zc:__cplusplus # flags to pass to the compiler in all builds

    Crt_rel:    dll     # [static | dll] type of CRT to link to in release builds
    Crt_dbg:    dll     # [static | dll] type of CRT to link to in debug builds

    IncDirs:    precompile;../include
    TargetDir:  ../lib

Files:
    ttconsole.cpp    # class that sets/restores console foreground color
    ttcstr.cpp       # Class for handling zero-terminated char strings.
    ttcvector.cpp    # Vector class for storing ttlib::cstr strings
    ttcview.cpp      # string_view functionality on a zero-terminated char string.
    ttenumstr.cpp    # ttEnumStr, ttEnumStr
    ttlibspace.cpp   # ttlib namespace functions
    ttparser.cpp     # Command line parser
    ttstrings.cpp    # Class for handling zero-terminated char strings.
    tttextfile.cpp   # Classes for reading and writing text files.
    ttTR.cpp         # Function for translating strings
