# Requires ttBld.exe version 1.5.0 or higher to process

Options:
    Project:    ttLib   # project target name
    Exe_type:   lib        # [window | console | lib | dll]
    Pch:        pch.h      # precompiled header
    Optimize:   space      # [space | speed] optimization
    Warn:       4          # [1-4]

    CFlags_cmn: -std:c++17 /Zc:__cplusplus # flags to pass to the compiler in all builds
    CFlags_dbg: /JMC

    Crt_rel:    dll        # [static | dll] type of CRT to link to in release builds
    Crt_dbg:    dll        # [static | dll] type of CRT to link to in debug builds

    IncDirs:    winsrc/precompile;../include
    TargetDir:  ../lib

Files:
    ttconsole.cpp    # class that sets/restores console foreground color
    ttcstr.cpp       # Class for handling zero-terminated char strings.
    ttcview.cpp      # string_view functionality on a zero-terminated char string.
    ttenumstr.cpp    # ttEnumStr, ttEnumStr
    ttlibspace.cpp   # ttlib namespace functions
    ttpath.cpp       # Contains functions for working with filesystem::path and filesystem::directory
    ttnamespace.cpp  # tt namespace functions
    tttextfile.cpp   # Classes for reading and writing text files.
    ttTR.cpp         # Function for translating strings
    ttcvector.cpp    # Vector class for storing ttlib::cstr strings

# Windows only files

    winsrc/ttdib.cpp           # ttCDib class
    winsrc/ttdirdlg.cpp        # dialog for selecting a directory
    winsrc/ttfiledlg.cpp       # ttCFileDlg class
    winsrc/ttloadstr.cpp       # Load a language-specific version of a string resource
    winsrc/ttmultibtn.cpp      # ttlib::MultiBtn class
    winsrc/ttshadebtn.cpp      # ttCShadeBtn class
    winsrc/ttthrdpool.cpp      # ttlib::ThrdPool
    winsrc/ttwin.cpp           # ttCWin class

    winsrc/ttdebug.cpp         # debug and assertion handling
    winsrc/ttwindlg.cpp        # Class for creating a Modal or Modeless dialog box
    winsrc/ttwinspace.cpp      # Windows-only ttlib namespace functions
