# Requires ttBld.exe version 1.4.0 or higher to process

Options:
    Project:    ttLibwin   # project target name
    Exe_type:   lib        # [window | console | lib | dll]
    Pch:        pch.h      # precompiled header
    Optimize:   space      # [space | speed] optimization
    Warn:       4          # [1-4]

    CFlags_cmn: -std:c++17 /Zc:__cplusplus # flags to pass to the compiler in all builds

    Crt_rel:    dll        # [static | dll] type of CRT to link to in release builds
    Crt_dbg:    dll        # [static | dll] type of CRT to link to in debug builds

    IncDirs:    ../src/winsrc/precompile;../include
    TargetDir:  ../lib

Files:

# The ../src/ files used to build ttLib.lib

    ../src/ttconsole.cpp    # class that sets/restores console foreground color
    ../src/ttcstr.cpp       # Class for handling zero-terminated char strings.
    ../src/ttcview.cpp      # string_view functionality on a zero-terminated char string.
    ../src/ttenumstr.cpp    # ttEnumStr, ttEnumStr
    ../src/ttformat.cpp     # ttString::Printf(...)
    ../src/ttlibspace.cpp   # ttlib namespace functions
    ../src/ttpath.cpp       # Contains functions for working with filesystem::path and filesystem::directory
    ../src/ttnamespace.cpp  # tt namespace functions
    # ../src/ttstring.cpp     # std::string class with some additional functionality
    ../src/tttextfile.cpp   # Classes for reading and writing text files.
    ../src/ttTR.cpp         # Function for translating strings
    ../src/ttcvector.cpp    # Vector class for storing ttlib::cstr strings

    # These files should be moved to ../src once they can be compiled/used without Windows

    ../src/winsrc/ttbasethread.cpp    # ttCBaseThread class
    ../src/winsrc/ttmultithread.cpp   # ttCMultiThrd class

# Windows only files

    ../src/winsrc/ttdebug.cpp         # debug and assertion handling
    ../src/winsrc/ttdib.cpp           # ttCDib class
    ../src/winsrc/ttdirdlg.cpp        # dialog for selecting a directory
    ../src/winsrc/ttdlg.cpp           # ttCDlg class
    ../src/winsrc/ttfiledlg.cpp       # ttCFileDlg class
    ../src/winsrc/ttmultibtn.cpp      # ttCMultiBtn class
    ../src/winsrc/ttshadebtn.cpp      # ttCShadeBtn class
    ../src/winsrc/ttwin.cpp           # ttCWin class
    ../src/winsrc/ttwindlg.cpp        # Class for creating a Modal or Modeless dialog box
    ../src/winsrc/ttwinspace.cpp      # Windows-only ttlib namespace functions

# The following modules are slated for removal as soon as all callers stop using them.

    ../src/winsrc/ttfile.cpp          # ttCFile class
    ../src/winsrc/ttfiledir.cpp       # file and directory handling
    ../src/winsrc/tthashpair.cpp      # ttCHashPair
    ../src/winsrc/ttheap.cpp          # ttCHeap class
    ../src/winsrc/ttlinefile.cpp      # Line-oriented file class
    ../src/winsrc/ttlist.cpp          # ttCList class
    ../src/winsrc/ttmisc.cpp          # miscellaneous functions
    ../src/winsrc/ttprintf.cpp        # printf
    ../src/winsrc/ttstr.cpp           # ttCStr class
    ../src/winsrc/ttstrfuncs.cpp      # C-style string handling
    ../src/winsrc/ttwinmisc.cpp       # Miscellaneous functions for use on Windows
    ../src/winsrc/ttwstr.cpp          # Wide-character string class
    ../src/winsrc/ttxml.cpp
