# Requires ttBld.exe version 1.4.0 or higher to process

Options:
    Project:    ttLibwin   # project target name
    Exe_type:   lib        # [window | console | lib | dll]
    Pch:        pch.h      # precompiled header
    Optimize:   space      # [space | speed] optimization
    Warn:       4          # [1-4]

    CFlags_cmn: -std:c++17 /Zc:__cplusplus # flags to pass to the compiler in all builds

    Crt_rel:    dll        # [static | dll] type of CRT to link to in release builds
    Crt_dbg:    dll        # [static | dll] type of CRT to link to in debug builds

    IncDirs:    precompile;../include
    TargetDir:  ../lib

Files:

# The ../src/ files used to build ttLib.lib

    ../src/ttconsole.cpp    # class that sets/restores console foreground color
    ../src/ttcstr.cpp       # Class for handling zero-terminated char strings.
    ../src/ttcview.cpp      # string_view functionality on a zero-terminated char string.
    ../src/ttenumstr.cpp    # ttEnumStr, ttEnumStr
    ../src/ttformat.cpp     # ttString::Printf(...)
    ../src/ttlibspace.cpp   # ttlib namespace functions
    ../src/ttpath.cpp       # Contains functions for working with filesystem::path and filesystem::directory
    ../src/ttnamespace.cpp  # tt namespace functions
    ../src/ttstring.cpp     # std::string class with some additional functionality
    ../src/tttextfile.cpp   # Classes for reading and writing text files.
    ../src/ttTR.cpp         # Function for translating strings
    ../src/ttcvector.cpp    # Vector class for storing ttlib::cstr strings

    # These files should be moved to ../src once they can be compiled/used without Windows

    ttbasethread.cpp    # ttCBaseThread class
    ttmultithread.cpp   # ttCMultiThrd class

# Windows only files

    ttdebug.cpp         # debug and assertion handling
    ttdib.cpp           # ttCDib class
    ttdirdlg.cpp        # dialog for selecting a directory
    ttdlg.cpp           # ttCDlg class
    ttfiledlg.cpp       # ttCFileDlg class
    ttmultibtn.cpp      # ttCMultiBtn class
    ttshadebtn.cpp      # ttCShadeBtn class
    ttwin.cpp           # ttCWin class
    ttwinspace.cpp      # Windows-only ttlib namespace functions

# The following modules are slated for removal as soon as all callers stop using them.

    ttfile.cpp          # ttCFile class
    ttfiledir.cpp       # file and directory handling
    tthashpair.cpp      # ttCHashPair
    ttheap.cpp          # ttCHeap class
    ttlinefile.cpp      # Line-oriented file class
    ttlist.cpp          # ttCList class
    ttmisc.cpp          # miscellaneous functions
    ttprintf.cpp        # printf
    ttstr.cpp           # ttCStr class
    ttstrfuncs.cpp      # C-style string handling
    ttwinmisc.cpp       # Miscellaneous functions for use on Windows
    ttwstr.cpp          # Wide-character string class
    ttxml.cpp
