# Requires ttBld.exe version 1.4.0 or higher to process

Options:
    Project:    ttLibwin   # project target name
    Exe_type:   lib        # [window | console | lib | dll]
    Pch:        pch.h      # precompiled header
    Optimize:   space      # [space | speed] optimization
    Warn:       4          # [1-4]

    CFlags_cmn: -std:c++17 /Zc:__cplusplus # flags to pass to the compiler in all builds

    Crt_rel:    dll        # [static | dll] type of CRT to link to in release builds
    Crt_dbg:    dll        # [static | dll] type of CRT to link to in debug builds

    IncDirs:    precompile;../include
    TargetDir:  ../lib

Files:
    # These files should be moved to ../src once they can be compiled without Windows

    ttbasethread.cpp    # ttCBaseThread class
    tthashpair.cpp      # ttCHashPair
    ttmultithread.cpp   # ttCMultiThrd class
    ttprintf.cpp        # printf
    ttstr.cpp           # ttCStr class
    ttmisc.cpp          # miscellaneous functions
    ttstrfuncs.cpp      # string handling and ttStr class

    # This is obsolete and should be replaced with pugixml!
    ttxml.cpp

    # This is obsolete and should be replaced by ttTextFile or ttTextView
    ttlinefile.cpp

# Windows only files

    ttdebug.cpp         # debug and assertion handling
    ttdib.cpp           # ttCDib class
    ttdirdlg.cpp        # dialog for selecting a directory
    ttdlg.cpp           # ttCDlg class
    ttfile.cpp          # ttCFile class
    ttfiledir.cpp       # file and directory handling
    ttfiledlg.cpp       # ttCFileDlg class
    ttheap.cpp          # ttCHeap class
    ttlist.cpp          # ttCList class
    ttmultibtn.cpp      # ttCMultiBtn class
    ttshadebtn.cpp      # ttCShadeBtn class
    ttwin.cpp           # ttCWin class
    ttwinmisc.cpp       # Miscellaneous functions for use on Windows
    ttwinspace.cpp      # Windows-only ttlib namespace functions
    ttwstr.cpp          # Wide-character string class
