name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - run: mkdir ${{github.workspace}}/build/Release

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - uses: actions/upload-artifact@v2
      with:
        name: ttLibWin
        path: ${{github.workspace}}/build/Release/ttLibWin.lib

    - name: Download ttLibWin
      uses: actions/download-artifact@v2
      with:
        name: ttLibWin
