name: Verify clang-format

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows
      - icons

  pull_request:
    paths-ignore:
      - .github/workflows
      - icons

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: '.'
        exclude: file
        extensions: 'h,cpp'
        clangFormatVersion: 12
        style: file
