name: Verify clang-format

on:
  push:
    paths-ignore:
    - .github/workflows

  pull_request:
    paths-ignore:
    - .github/workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.12
      with:
        source: './src'
        exclude: file
        extensions: 'h,cpp'
        clangFormatVersion: 12
        style: file
